language: node_js
node_js:
  - "lts/*"
services: mysql
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE sho6;'
  - cd client
script:
  - cd ../server
  - npm install
  - echo '{"host":"127.0.0.1","user":"root","database":"sho6"}' > db.json
  - npm start & wait-on http://localhost:8180
  - cd ../client
  - yarn start & wait-on http://localhost:3000
  - cypress run