language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
before_install:
  - cd client
script:
  - cd ../server
  - npm install
  - npm start & wait-on http://localhost:8180
  - cd ../client
  - yarn start & wait-on http://localhost:3000
  - cypress run